### ISSUE TITLE
Certificate apparently wrong for https://iuscommunity.org/

### ISSUE THREAD

**Issue by guilhox** [iuscommunity/infrastructure#19]
Hello,

When trying to access https://iuscommunity.org/ or download any dependencies from https://centos6.iuscommunity.org/ius-release.rpm, the website returns a certificate which seems to be from another site.
![image](https://user-images.githubusercontent.com/3399821/92609644-31522900-f28d-11ea-85a7-cfaceb256f9c.png)

Additionally, even when ignoring certificates, it requires authentication, which it didn't before.

**Comment by carlwgeorge** [comment]
Regarding https://iuscommunity.org, our website has been hosted at https://ius.io since 2014.  It looks like we forgot to remove the DNS A and AAAA records, and the IP addresses those pointed to have been recycled by our hosting provider.  I have removed those DNS records.

Regarding https://centos6.iuscommunity.org/ius-release.rpm, that was part of our old redirect service.  It was replaced with symlinks on our CDN in [2019-05](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-488866147), but kept online until [2020-05](https://github.com/iusrepo/announce/issues/18).  We also forgot to remove those DNS records, which I have now done.

If you use IUS, please subscribe to our [announce repository](https://github.com/iusrepo/announce) to be notified of changes like these.
